# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    name: pygtc CI python ${{ matrix.python-version }} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
          activate-environment: pygtc-test
          environment-file: test-environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
    - shell: bash -l {0}
      run: |
        pytest --mpl